// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCXGbgltOfd_ED-NbhTZKKgJDv7gwMI5E',
    appId: '1:917662206166:web:96c523a6cc814864e9e177',
    messagingSenderId: '917662206166',
    projectId: 'smarthealth-7c67a',
    authDomain: 'smarthealth-7c67a.firebaseapp.com',
    storageBucket: 'smarthealth-7c67a.firebasestorage.app',
    measurementId: 'G-33VY1Z9BN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOK7Cxjg-_Ci9vXfXwW53rvCVkemOcRAY',
    appId: '1:917662206166:android:01eaea28174e99ede9e177',
    messagingSenderId: '917662206166',
    projectId: 'smarthealth-7c67a',
    storageBucket: 'smarthealth-7c67a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhXel9W4DIuqYfffLPg2aEZr555sk6oY',
    appId: '1:917662206166:ios:50cc383dfdb04ea0e9e177',
    messagingSenderId: '917662206166',
    projectId: 'smarthealth-7c67a',
    storageBucket: 'smarthealth-7c67a.firebasestorage.app',
    iosBundleId: 'com.example.smarthealthApp',
  );
}
